### ISSUE TITLE
Failed to build module 'IDNowSDKCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.2 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.

### ISSUE THREAD

**Issue by Aaqibali279** [idnow/de.idnow.ios.sdk.spm#18]
on xcode 13.2.1

Failed to build module 'IDNowSDKCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.2 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.

please provide a version that has Library Evolution enabled
like 
$ swiftc Tack.swift Barn.swift Hay.swift \
    -module-name Horse \
    -emit-module -emit-library -emit-module-interface \
    -enable-library-evolution

**Comment by deryck-tomiuc-idnow** [comment]
Hello @Aaqibali279,
Thank you for reaching us. Let me get back to you as soon as we have a fix for this. 
Thank you!

**Comment by Aaqibali279** [comment]
@deryck-tomiuc-idnow we need sdk that gives statusCode on

IDNowSDK.shared.start(token: token, preferredLanguage:"en", fromViewController: self, listener:{(result: IDNowSDK.IdentResult.type, statusCode: IDNowSDK.IdentResult.statusCode, message: String) in
            if result == .ERROR {
                self.showAlert(text: statusCode.description)
            } else if result == .FINISHED {
                
            }
        })

4.19.1 version is not giving statusCode

**Comment by deryck-tomiuc-idnow** [comment]
Understood. In this case, I will try to prioritize this.

**Comment by deryck-tomiuc-idnow** [comment]
Hello @Aaqibali279,
After doing some research on this topic I can definitely say library-evolution is activated within IDNowSDK. You can check the flag into the public `.swiftinterface`  file, from the `Modules` folder within the SDK framework. From my findings, prior to Swift 5.1, you were not able to use compiled binary (compiled with an older version of swift compiler), on a newer one. As an example, you could not compile binary that has been compiled with 4.8 on 4.9 compiler. This has been changed with swift 5.1, were you can do this, using this library-evolution flag and skip_install one. But, the problem you are having is not the same.
Your compiler version (XCode 13.4.1, Swift 5.6.1) cannot know the instructions that the new one introduced. It can compile < 5.6.1, but not above.
Starting IDNowSDK version 5.0.0, we compile with XCode 14.1 (Swift 5.7.1) which has new instructions unknown to your compiler (5.6.1).
I will suggest you to update to XCode 14.1, which is a stable release, were you can use the IDNowSDK without any compilation issues.
Please let me know if I can offer more informations on this topic.
Thank you!

**Comment by Aaqibali279** [comment]
@deryck-tomiuc-idnow  but i am not able to run my project in xcode 14.1, could you please make sdk version 5.0.1 compilable on xcode 13+

**Comment by deryck-tomiuc-idnow** [comment]
I will have to pass this internally to the PO and get back to you. Thank you!

**Comment by Aaqibali279** [comment]
@deryck-tomiuc-idnow yes please, thank you!

**Comment by mrsamse** [comment]
Same compiler error for me. Also tried version 4.19.1 out and it didn't work with that either.

**Comment by deryck-tomiuc-idnow** [comment]
Hello @Aaqibali279, @mrsamse,
Can you both please try `release/5.0.1-xcode13.4.1` and let me know if you are having any issues.
Thank you!

**Comment by Aaqibali279** [comment]
@deryck-tomiuc-idnow i am able to run the app now on xcode 13.4.1 with release/5.0.1

but idnow is not opening 

stack trace below:

IDNOW SDK started. Token:  TST-NCMXR
2022-11-27 22:47:28.421481-0800 idnow_test[20494:602662] Metal API Validation Enabled
loadGifAssetFile: inexist
loadGifAssetFile: loading new one
22:47:28.631 | IdentOrchestrator | Preparing ...
loadGifAssetFile: end loading
22:47:28.633 | IdentOrchestrator | Getting Ident Info ...
22:47:39.719 | IdentOrchestrator | Getting Ident Info failed
2022-11-27 22:47:39.719818-0800 idnow_test[20494:602662] [Insights] SDK should be started first!
2022-11-27 22:47:39.719924-0800 idnow_test[20494:602662] [Insights] SDK should be started first!
statusCode
type

**Comment by deryck-tomiuc-idnow** [comment]
Hello @Aaqibali279,
From what I see, too many request had been made using that token. Please generate a new one and try again and let me know if you are having the same issue.
No need to send me the log, just the status code that you are receiving.
Thank you!

**Comment by Aaqibali279** [comment]
@deryck-tomiuc-idnow  working now

**Comment by deryck-tomiuc-idnow** [comment]
@Aaqibali279, can we close this issue?

**Comment by Aaqibali279** [comment]
yes

**Comment by deryck-tomiuc-idnow** [comment]
@Aaqibali279 you will need to close it with the dedicated "Close Issue" button. Thank you!

**Comment by mrsamse** [comment]
Works for me too now! Thx guys.
