### ISSUE TITLE
SDK not compatible with Xcode 14.1

### ISSUE THREAD

**Issue by 7-plus-t** [idnow/de.idnow.ios.sdk.spm#20]
Version: 5.0.1
Type: With NFC
Xcode: 14.1 (14B47b)

When building the SDK I get the following error:
```
Failed to build module 'IDNowSDKCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.2 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)'). Please select a toolchain which matches the SDK.
```

Could you please release an updated version of the SDK compatible with Xcode 14.1?

**Comment by deryck-tomiuc-idnow** [comment]
Hello @7-plus-t,
Thank you for reaching us. I will need to check this because the 5.0.1 has been built for XCode 14+.
Will get back to you as soon as possible.
Thank you!

**Comment by deryck-tomiuc-idnow** [comment]
Hello @7-plus-t, Are you having the same problem with 5.0.4? Regards.

**Comment by luciansvnc** [comment]
I still have this issue with Xcode 14.2.

**Comment by 7-plus-t** [comment]
@deryck-tomiuc-idnow works for me with 5.0.5
