### ISSUE TITLE
Swift package manager implementation didnt work

### ISSUE THREAD

**Issue by klawsachkar** [idnow/de.idnow.ios.sdk.spm#3]
We have tried to migrate our SDK to Swift Package manager but we got two issues:

1- in the file "Package.swift" we got the below error
![MicrosoftTeams-image (18)](https://user-images.githubusercontent.com/3592933/157856348-5a2d57aa-d97e-4d78-9604-4737ee6af1b0.png)

2- the pod library Sentry is still required since we got an error when we removed it referring to the documentation
  `pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.1.0'`

**Comment by BilelSelmiIDnow** [comment]
@klawsachkar : can you please provide a sample project reproducing the issue.

Thanks

**Comment by klawsachkar** [comment]
can you double check the two issues described above? it is not a new project that i can share, and the code is confidential.

we used to have the below pods together:
```
pod 'OpenCV2',                  '~> 3.4.1'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.1.0'
```

and we copy IDNowSDKCore and FaceTecSDK into the code in order to make it work.

Now with SPM, the issues are described above, and we cannot continue.
