### ISSUE TITLE
artifact not found for target 'IDnowSDKCore-with-NFC'

### ISSUE THREAD

**Issue by jiheneme** [idnow/de.idnow.ios.sdk.spm#4]
Hello,

I'm facing a build problem in xcode 13.3 : 
Missing package product 'IDnowSDKCore-without-NFC'
Artifact not found for target 'IDnowSDKCore-with-NFC'

Someone have an idea about this please ?

Thanks in advance.
Jihène

**Comment by mtidnow** [comment]
Hi, jiheneme
the issue was fixed in the latest release.
